from pathlib import Path
from dotenv import load_dotenv
load_dotenv(
    dotenv_path=Path(__file__).resolve().parent / ".env",
    override=True,
)

PHOTO_UPLOAD_EXTEND_MINUTES = 60
VIDEO_UPLOAD_EXTEND_MINUTES = 360
OTHERS_UPLOAD_EXTEND_MINUTES = 360

INACTIVE_EXPIRE_DAYS = 5  # 通行证过期超过此天数后，可由管理员清理
MEDIA_REWARD_EXTEND_MINUTES = 60  # 每个媒体奖励增加的分钟数

HOURLY_CONSUMPTION_MINUTES = 60
MESSAGE_REWARD_MINUTES = 60
MEDIA_UPLOAD_EXTEND_MINUTES = 360   #每个媒体增加六小时(360min)
MEDIA_VIEW_CONSUMPTION_MINUTES = 60
MAX_HP_CAPACITY_MINUTES = 1440 * INACTIVE_EXPIRE_DAYS

HOURLY_CONSUMPTION_QUANTITY = HOURLY_CONSUMPTION_MINUTES // 60
MESSAGE_REWARD_QUANTITY = MESSAGE_REWARD_MINUTES // HOURLY_CONSUMPTION_MINUTES
MEDIA_UPLOAD_EXTEND_QUANTITY = MEDIA_UPLOAD_EXTEND_MINUTES // HOURLY_CONSUMPTION_MINUTES
MEDIA_VIEW_CONSUMPTION_QUANTITY = MEDIA_VIEW_CONSUMPTION_MINUTES // HOURLY_CONSUMPTION_MINUTES
MAX_HP_CAPACITY_QUANTITY = MAX_HP_CAPACITY_MINUTES // HOURLY_CONSUMPTION_MINUTES

IGNORED_TEXT_SUBSTRINGS = (
	"早上好",
	"早安",
	"大家好",
	"早早",
	"早啊",
	"中午好",
	"下午好",
	"晚上好",
	"晚好",
	"凌晨好",
	"新的一天",
	"起飞",
	"飞飞飞",
	"发个言",
	"爬楼",
	"打卡",
	"撸个管",
	"插眼"
)

